### ISSUE TITLE
Use Document Format Hook

### ISSUE THREAD

**Issue by superlinkx** [fterrag/vscode-php-cs-fixer#3]
The onSave method does not hook in as cleanly as other formatting extensions, due to it firing even when autosave is enabled. As a result, if autosave is enabled and you accidentally input something into a document you don't want to have formatted with this extension, it will cause a format, and undoing will cause it to format again.

The best fix would be to integrate with VSCode's format document command, which is actually sensitive to autosave vs real save, as well as being a cleaner implementation and more in line with other formatting extensions.

**Comment by fterrag** [comment]
Hi @superlinkx! Thanks for the suggestion - I will look into this when I have some free time.

**Comment by garygreen** [comment]
I believe this is in relation to `workspace.onWillSaveTextDocument` and `languages.registerDocumentFormattingEditProvider`

You can read more about it here: https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices

@jrieken sorry to ping, but do you have any info on how we could implement this for this extension?

**Comment by fterrag** [comment]
@garygreen thanks for the info. I know I've let this issue sit for some time, but I am still interested in making the right changes here. I think I'll have some time this weekend to take a deeper look. Thanks!

**Comment by garygreen** [comment]
@fterrag thanks so much. I think once this is resolved, it'll help prevent these frustrating errors that pop up when your saving a document in quick succession multiple times before the fixer has finished running:

![image](https://user-images.githubusercontent.com/1702638/53265784-fc947600-36d6-11e9-9de3-fd70928d5051.png)

I don't believe a lot needs to be changed for it to work with vscodes built in formatter.. but if you can find time to take a look that would be much appreciated 👍

**Comment by garygreen** [comment]
FYI - it doesn't look like we'll be able to gracefully handle fix on save without some errors, as in the screenshot above, until php-cs-fixer implements stdout. See https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2011

Though it maybe possible to delay attempting to send multiple fixDocument calls before cs-fixer has finished the last one (and vscode has re-loaded the document)

**Comment by garygreen** [comment]
@fterrag I've submitted a [PR to add stdout support for php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4320). Would you do me a favour and go there and show some support/love for it? This PR would massively benefit this extension because it means we can then pipe stdin to php-cs-fixer then stdout into vscode, avoiding multiple disk saves and make it easier to prevent the "Failed to save" error in vscode

**Comment by fterrag** [comment]
@superlinkx @garygreen this issue has been addressed in 0.3.0. This should resolve the "The content on disk is newer." error. Thanks guys!

**Comment by garygreen** [comment]
@fterrag thanks for that. Though it doesn't resolve the "content on disk is newer" error - that can only really be solved with stdout support for cs-fixer and had a bit of trouble trying to get that merged in. Maybe worth using a forked version?

**Comment by fterrag** [comment]
@garygreen that issue has been solved by the use of a temporary file. See https://github.com/fterrag/vscode-php-cs-fixer/blob/master/extension.js#L43

**Comment by fterrag** [comment]
@garygreen that issue has been resolved by the use of a temporary file. See https://github.com/fterrag/vscode-php-cs-fixer/blob/master/extension.js#L43
